import { Project } from '@/types/project';

// Datos originales del sitio - FALLBACK si no hay Supabase
export const FALLBACK_PROJECTS: Project[] = [
  {
    id: '1',
    title: "La Joya Del Pantano",
    description: "Trailer de la historia original La Joya Del Pantano",
    video_url: "https://vimeo.com/896578269?fl=pl&fe=sh",
    category: "2d",
    images: [
      '/images/megaCard/LaJoyaDelPantano/LJDP01.jpeg',
      '/images/megaCard/LaJoyaDelPantano/LJDP02.jpeg',
      '/images/megaCard/LaJoyaDelPantano/LJDP03.jpeg',
    ],
    is_featured: true,
    featured_order: 1,
    featured_poster: '/images/projects/LJDP_HD_FULL_DEFF.webp',
    featured_description: 'Historia original de Spiriwors que combina la magia del stop-motion con una narrativa emotiva sobre la naturaleza y la aventura.',
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: "SALÚ",
    description: "Trailer de la historia original SALÚ",
    video_url: "https://vimeo.com/172426682?fl=pl&fe=sh",
    category: "2d",
    images: [
      '/images/megaCard/Salu/Salu01.jpeg',
      '/images/megaCard/Salu/Salu02.jpeg',
      '/images/megaCard/Salu/Salu03.jpeg',
    ],
    is_featured: true,
    featured_order: 2,
    featured_poster: '/images/projects/SALU_AFICHE.webp',
    featured_description: 'Proyecto destacado de Spiriwors que muestra la creatividad y técnica única en animación, desarrollando mundos únicos para una experiencia inmersiva.',
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: "Un Bosque Encantado 2 – El Abrazo del Ciempiés",
    description: "Un Bosque Encantado 2 – El Abrazo del Ciempiés",
    video_url: "https://www.youtube.com/watch?v=qDt5k1NIWr0",
    category: "2d",
    images: [
      '/images/megaCard/Ciempies/Cien01.jpeg',
      '/images/megaCard/Ciempies/Cien02.jpeg',
      '/images/megaCard/Ciempies/Cien03.jpeg',
    ],
    is_featured: false,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: "Un Bosque Encantado 2 – Lobos",
    description: "Un Bosque Encantado 2 – Lobos",
    video_url: "https://www.youtube.com/watch?v=zQM8IrGu5Oo",
    category: "2d",
    images: [
      '/images/megaCard/Lobos/Lobos01.jpeg',
      '/images/megaCard/Lobos/Lobos02.jpeg',
      '/images/megaCard/Lobos/Lobos03.jpeg',
    ],
    is_featured: false,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: "AJR – My Play",
    description: "Cargo: animación – Camilo Ayala. A Creative Service by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/my-play-ajr/",
    category: "2d",
    images: [
      '/images/megaCard/AJR/Ajr01.jpeg',
      '/images/megaCard/AJR/Ajr02.jpeg',
      '/images/megaCard/AJR/Ajr03.jpeg',
    ],
    is_featured: false,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: "ONR – It Gets To a Point",
    description: "Cargo: animación – Camilo Ayala. A Creative Service by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/it-gets-to-a-point-onr/",
    category: "2d",
    images: [
      '/images/megaCard/ONR/ONR01.jpeg',
      '/images/megaCard/ONR/ONR02.jpeg',
      '/images/megaCard/ONR/ONR03.jpeg',
    ],
    is_featured: false,
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: "We The Kingdom – Christmas In Hawaii",
    description: "Cargo: modelado de marionetas y animación stop-motion – Camilo Ayala. A Creative Service by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/christmas-in-hawaii-we-the-kingdom/",
    category: "stop",
    images: [
      '/images/megaCard/Christmas/Ch01.jpeg',
      '/images/megaCard/Christmas/Ch02.jpeg',
      '/images/megaCard/Christmas/Ch03.jpeg',
    ],
    is_featured: false,
    display_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: "Satellite – Bebe Rexha & Snoop Dogg",
    description: "Cargo: animación. A Creative Service by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/satellite-bebe-rexha-snoop-dogg/",
    category: "2d",
    images: [
      '/images/megaCard/SnoopDogg/SD01.jpeg',
      '/images/megaCard/SnoopDogg/SD02.jpeg',
      '/images/megaCard/SnoopDogg/SD03.jpeg',
    ],
    is_featured: false,
    display_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: "Waldo´s Dream",
    description: "Cargo: animación. A Creative Service by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/waldos-dream/",
    category: "2d",
    images: [
      '/images/megaCard/Waldo´sDream/WD01.jpeg',
      '/images/megaCard/Waldo´sDream/WD02.jpeg',
      '/images/megaCard/Waldo´sDream/WD03.jpeg',
    ],
    is_featured: false,
    display_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: "Heroes Collection: Francis Ford Coppola",
    description: "Cargo: Realizador de Animatic y Animador – Camilo Ayala. Original Content by Venturia Animation Studios. All Rights Reserved.",
    video_url: "https://venturiaanimation.com/portfolio/heroes-francis-ford-coppola/",
    category: "2d",
    images: [
      '/images/megaCard/Coppola/Coppola01.jpeg',
      '/images/megaCard/Coppola/Coppola02.jpeg',
      '/images/megaCard/Coppola/Coppola03.jpeg',
    ],
    is_featured: false,
    display_order: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: "Smiling Symphonies",
    description: "Proyecto de Dinamita Animación – Smiling Symphonies",
    video_url: "https://dinamitaanimacion.com/portfolio/smiling-symphonies/",
    category: "2d",
    images: [
      '/images/megaCard/Smiling/S_Sy01.jpeg',
      '/images/megaCard/Smiling/S_Sy02.jpeg',
      '/images/megaCard/Smiling/S_Sy03.jpeg',
    ],
    is_featured: false,
    display_order: 11,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
